Add Map::remove_entry
serde-rs/json pull request #708
Opened 2020-09-18 09:55 UTC by jplatte

… and simplify `Map::remove`, since I noticed it uses `#[cfg]` branching when it doesn't need to.

2020-09-18 10:28 UTC, jplatte commented
Okay so `BTreeMap::remove_entry` is only available since 1.45.0. Would feature-gating stuff like this that requires a higher MSRV be an option?

2020-09-30 17:01 UTC, jplatte commented
@dtolnay It's now behind a feature flag that is also tested on CI. Can you take a look?

2020-09-30 18:37 UTC, dtolnay requested changes
I would prefer not to do feature stuff for this. It would be better to emulate the API if remove_entry is not directly available on the underlying type. Is that possible?

2020-09-30 18:41 UTC, jplatte commented
No, unfortunately I don't think that is possible. The entry API requires taking ownership of the key which defeats the whole point, and a raw entry API is only available for HashMap, not BTreeMap.

2020-09-30 20:34 UTC, dtolnay commented
Closing in favor of #712 which emulates the API when remove_entry is not available on the underlying type.

2020-09-30 20:34 UTC, closed without merging

2020-09-30 21:20 UTC, jplatte commented
I see, so using a less efficient implementation on older versions. I like that :+1: